from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeleteResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, id=None):  # noqa: E501
        """DeleteResponse - a model defined in OpenAPI

        :param message: The message of this DeleteResponse.  # noqa: E501
        :type message: str
        :param id: The id of this DeleteResponse.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'message': str,
            'id': int
        }

        self.attribute_map = {
            'message': 'message',
            'id': 'id'
        }

        self._message = message
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteResponse of this DeleteResponse.  # noqa: E501
        :rtype: DeleteResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this DeleteResponse.


        :return: The message of this DeleteResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this DeleteResponse.


        :param message: The message of this DeleteResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def id(self) -> int:
        """Gets the id of this DeleteResponse.


        :return: The id of this DeleteResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this DeleteResponse.


        :param id: The id of this DeleteResponse.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
