from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateBookRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, published_year=None):  # noqa: E501
        """UpdateBookRequest - a model defined in OpenAPI

        :param title: The title of this UpdateBookRequest.  # noqa: E501
        :type title: str
        :param author: The author of this UpdateBookRequest.  # noqa: E501
        :type author: str
        :param published_year: The published_year of this UpdateBookRequest.  # noqa: E501
        :type published_year: int
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'published_year': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'published_year': 'published_year'
        }

        self._title = title
        self._author = author
        self._published_year = published_year

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateBookRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateBookRequest of this UpdateBookRequest.  # noqa: E501
        :rtype: UpdateBookRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this UpdateBookRequest.


        :return: The title of this UpdateBookRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this UpdateBookRequest.


        :param title: The title of this UpdateBookRequest.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this UpdateBookRequest.


        :return: The author of this UpdateBookRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this UpdateBookRequest.


        :param author: The author of this UpdateBookRequest.
        :type author: str
        """

        self._author = author

    @property
    def published_year(self) -> int:
        """Gets the published_year of this UpdateBookRequest.


        :return: The published_year of this UpdateBookRequest.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this UpdateBookRequest.


        :param published_year: The published_year of this UpdateBookRequest.
        :type published_year: int
        """
        if published_year is not None and published_year < 0:  # noqa: E501
            raise ValueError("Invalid value for `published_year`, must be a value greater than or equal to `0`")  # noqa: E501

        self._published_year = published_year
