from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductListResponsePagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, limit=None, total_items=None, total_pages=None):  # noqa: E501
        """ProductListResponsePagination - a model defined in OpenAPI

        :param page: The page of this ProductListResponsePagination.  # noqa: E501
        :type page: int
        :param limit: The limit of this ProductListResponsePagination.  # noqa: E501
        :type limit: int
        :param total_items: The total_items of this ProductListResponsePagination.  # noqa: E501
        :type total_items: int
        :param total_pages: The total_pages of this ProductListResponsePagination.  # noqa: E501
        :type total_pages: int
        """
        self.openapi_types = {
            'page': int,
            'limit': int,
            'total_items': int,
            'total_pages': int
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total_items': 'totalItems',
            'total_pages': 'totalPages'
        }

        self._page = page
        self._limit = limit
        self._total_items = total_items
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'ProductListResponsePagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductListResponse_pagination of this ProductListResponsePagination.  # noqa: E501
        :rtype: ProductListResponsePagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this ProductListResponsePagination.


        :return: The page of this ProductListResponsePagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this ProductListResponsePagination.


        :param page: The page of this ProductListResponsePagination.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501
        if page is not None and page < 1:  # noqa: E501
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this ProductListResponsePagination.


        :return: The limit of this ProductListResponsePagination.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this ProductListResponsePagination.


        :param limit: The limit of this ProductListResponsePagination.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501
        if limit is not None and limit < 1:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `1`")  # noqa: E501

        self._limit = limit

    @property
    def total_items(self) -> int:
        """Gets the total_items of this ProductListResponsePagination.


        :return: The total_items of this ProductListResponsePagination.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items: int):
        """Sets the total_items of this ProductListResponsePagination.


        :param total_items: The total_items of this ProductListResponsePagination.
        :type total_items: int
        """
        if total_items is None:
            raise ValueError("Invalid value for `total_items`, must not be `None`")  # noqa: E501
        if total_items is not None and total_items < 0:  # noqa: E501
            raise ValueError("Invalid value for `total_items`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total_items = total_items

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this ProductListResponsePagination.


        :return: The total_pages of this ProductListResponsePagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this ProductListResponsePagination.


        :param total_pages: The total_pages of this ProductListResponsePagination.
        :type total_pages: int
        """
        if total_pages is None:
            raise ValueError("Invalid value for `total_pages`, must not be `None`")  # noqa: E501
        if total_pages is not None and total_pages < 0:  # noqa: E501
            raise ValueError("Invalid value for `total_pages`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total_pages = total_pages
